#' Rotate a symbol
#'
#' Rotate a symbol for use with geom_symbol.
#'
#' @param recipe A string generated by `symbol_recipe()` or found in `symbol_lookup`.
#' @param degrees The degree of clockwise rotation desired, in degrees rather than radians.
#'
#' @returns A string in the same format as a `symbol_recipe()` output, for use with `geom_symbol()`
#' @export
#'
#' @examples
symbol_rotate <- function(recipe, degrees) {
  details <- symbol_recipe_to_list(recipe)
  radians <- -(degrees * (pi / 180))

  new_x <- (details$x * cos(radians)) - (details$y * sin(radians))
  new_y <- (details$y * cos(radians)) + (details$x * sin(radians))

  symbol_recipe(x = new_x, y = new_y, id = details$id)
}

#' Flip a symbol
#'
#' Mirror a symbol for use with geom_symbol.
#'
#' @param recipe A string generated by `symbol_recipe()` or found in `symbol_lookup`.
#' @param axis The axis for the symbol to be mirrored along. `x`, `y`, or `xy` for mirroring along both axes.
#'
#' @returns A string in the same format as a `symbol_recipe()` output, for use with `geom_symbol()`
#' @export
#'
#' @examples
symbol_flip <- function(recipe, axis = "x") {
  details <- symbol_recipe_to_list(recipe)

  if (axis == "x") {
    new_x <- details$x * -1
    new_y <- details$y
  } else if (axis == "y") {
    new_x <- details$x
    new_y <- details$y * -1
  } else if (axis == "xy") {
    new_x <- details$x * -1
    new_y <- details$y * -1
  } else {
    stop("axis value not recognised")
  }

  symbol_recipe(x = new_x, y = new_y, id = details$id)
}
