#' Rotate a symbol
#'
#' Rotate a symbol for use with geom_symbol.
#'
#' @param recipe A string generated by `symbol_recipe()` or found in `symbol_lookup`.
#' @param degrees The degree of clockwise rotation desired, in degrees rather than radians.
#'
#' @returns A string in the same format as a `symbol_recipe()` output, for use with `geom_symbol()`
#' @export
#'
#' @examples
symbol_rotate <- function(recipe, degrees) {
  details <- symbol_recipe_to_list(recipe)
  radians <- -(degrees * (pi / 180))

  new_x <- (details$x * cos(radians)) - (details$y * sin(radians))
  new_y <- (details$y * cos(radians)) + (details$x * sin(radians))

  symbol_recipe(x = new_x, y = new_y, id = details$id)
}
